### ISSUE TITLE
Name field in pubspec does not match

### ISSUE THREAD

**Issue by ride4sun** [perlatus/flutter_zoomable_image#12]
in order to reference this package I think the name in pubspec has to be the same as in the url.
URL: flutter_zoomable_image
PUBSPEC: zoomable_image

```
zoomable_image:
    git:
      url: https://github.com/perlatus/flutter_zoomable_image.git
```

Error on get Packages:

C:\sdks\flutter\bin\flutter.bat --no-color packages get
Running "flutter packages get" in lookatmybaby_flutter...
Error on line 1, column 7: "name" field doesn't match expected name "flutter_zoomable_image".
name: zoomable_image
      ^^^^^^^^^^^^^^

**Comment by perlatus** [comment]
Hmm, I'm not getting this even when I clear out my ~/.pub-cache. Can you upgrade your flutter and post your pubspec.yaml?
