### ISSUE TITLE
Need update to Dart SDK 2.x

### ISSUE THREAD

**Issue by Mythar** [perlatus/flutter_zoomable_image#17]
The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.

Because zoomable_image 1.2.0 requires SDK version >=1.19.0 <2.0.0 and no versions of zoomable_image match >1.2.0 <2.0.0, zoomable_image ^1.2.0 is forbidden.
So, because flutter_test_1 depends on zoomable_image ^1.2.0, version solving failed.
pub get failed (1)

**Comment by wesleyfantinel** [comment]
Yeah, it would be great to have support for 2.0. Looking forward for it, thanks!

**Comment by perlatus** [comment]
I merged a PR for this but haven't put out a pub build yet. Will do soon

**Comment by perlatus** [comment]
Should be fixed in 1.2.1+1 supporting < 3.0.0
